### ISSUE TITLE
Error in node_num_ind:(length(profile_data1)) : argument of length 0

### ISSUE THREAD

**Issue by safalabolo** [shoebodh/hydrusR#2]
Hi,
I performed a run with the h1d_flow_wtable.R script.
At one point I have an error: I can not understand where it comes from.
Thanks in advance for the support and your work!

Following the lines of my console:

R version 3.3.3 (2017-03-06) -- "Another Canoe"
Copyright (C) 2017 The R Foundation for Statistical Computing
Platform: x86_64-w64-mingw32/x64 (64-bit)

R is free software and comes with ABSOLUTELY NO WARRANTY.
You are welcome to redistribute it under certain conditions.
Type 'license()' or 'licence()' for distribution details.

R is a collaborative project with many contributors.
Type 'contributors()' for more information and
'citation()' on how to cite R or R packages in publications.

Type 'demo()' for some demos, 'help()' for on-line help, or
'help.start()' for an HTML browser interface to help.
Type 'q()' to quit R.

> library(hydrusR)
Carico il pacchetto richiesto: data.table
data.table 1.10.4.3
  The fastest way to learn (by data.table authors): https://www.datacamp.com/courses/data-analysis-the-data-table-way
  Documentation: ?data.table, example(data.table) and browseVignettes("data.table")
  Release notes, videos and slides: http://r-datatable.com
> library(data.table)
> library(dplyr)

Attaching package: ‘dplyr’

The following objects are masked from ‘package:data.table’:

    between, first, last

The following objects are masked from ‘package:stats’:

    filter, lag

The following objects are masked from ‘package:base’:

    intersect, setdiff, setequal, union

> TimeUnit = "cm" ## Space units
> SpaceUnit = "hours" ## time units
> PrintTimes = 1
> profile_depth = 200
> endTime = 500
> deltaz = 1
> rdepth = 100
> time_step = 0.25
> soil_para = list(thr = 0.045, ths = 0.43,
+                  Alfa = 0.145, n = 2.69, Ks = 29.7, l = 0.45)
> hydrus_path =  "C:/Program Files (x86)/PC-Progress/Hydrus-1D 4.xx"
> project_name = "h1dExample"
> parent_dir = path.expand("~")
> project_path = path.expand(file.path(parent_dir, project_name))
> rwu = T   ###  rootwater uptake
> profile_nodes = seq(0, profile_depth, by = deltaz)
> initial_wtable = 30
> obs_nodes_all = seq(20, profile_depth, by = 20)
> nObsNodes = length(obs_nodes_all)
> rooting_depth = 120
> total_timesteps = endTime/time_step
> ntimesteps = length(1:total_timesteps)
> input_pet = TRUE
> LAI = 4.0
> et_rate = 0.6
> const_botbc = TRUE
> bot_bc_type = "flux"
> const_botFlux = 0.0000 ##### in cm/hr
> atm_bc_data = data.frame(tAtm = seq(time_step, endTime, time_step),
+                          Prec = numeric(ntimesteps),
+                          rSoil = numeric(ntimesteps),
+                          rRoot = numeric(ntimesteps),
+                          hCritA = rep(10000, ntimesteps),
+                          rB = numeric(ntimesteps),
+                          hB = numeric(ntimesteps),
+                          ht = numeric(ntimesteps),
+                          RootDepth = numeric(ntimesteps))
> if(isTRUE(input_pet)) {
+       atm_bc_data$rRoot = rep(LAI, nrow(atm_bc_data))
+       atm_bc_data$rSoil = rep(et_rate/2, nrow(atm_bc_data))
+ } else {
+       atm_bc_data$rRoot = rep(et_rate/2, nrow(atm_bc_data))
+       atm_bc_data$rSoil = rep(et_rate/2, nrow(atm_bc_data))
+ 
+ }
> const_et = rep(et_rate, 365)
> hourly_et =  et.hourly(Et.Daily = const_et)
> hourly_et = hourly_et[rep(seq_len(nrow(hourly_et)), each = 1/time_step), ] ### for 0.25 time steps
> hourly_et$rSoil = hourly_et$et/2
> hourly_et$rRoot = hourly_et$et/2
> if(isTRUE(input_pet)) {
+       atm_bc_data$rRoot = rep(LAI, nrow(atm_bc_data))
+       atm_bc_data$rSoil = hourly_et$rSoil[1:nrow(atm_bc_data)]
+ } else {
+       atm_bc_data$rRoot = hourly_et$rRoot[1:nrow(atm_bc_data)]
+       atm_bc_data$rSoil = hourly_et$rSoil[1:nrow(atm_bc_data)]
+ 
+ }
> if(isTRUE(const_botbc)){
+       atm_bc_data$hB = rep(0, nrow(atm_bc_data))
+ }
> atm_bc_data = atm_bc_data[1:ntimesteps, ]
> create.H1D.project(project.name = project_name, parent.dir = parent_dir,
+                    TimeUnit = TimeUnit, PrintTimes = PrintTimes,
+                    processes = c(WaterFlow = T, RootWaterUptake = rwu),
+                    geometry = c(ProfileDepth = profile_depth,
+                                 NumberOfNodes = length(profile_nodes),
+                                 ObservationNodes = nObsNodes))
Folder h1dExample already exists.All files will be deleted.Proceed? y/n 
y
New H1DRUS-1D project create in C:/Users/Oscar/Documents/h1dExample ...
> create.soil.profile(project.path = project_path, out.file = "PROFILE.DAT",
+                     profile.depth = profile_depth, dz = deltaz)
> write.obs.nodes(project.path = project_path, obs.nodes = obs_nodes_all)
> write.ini.cond(project.path = project_path, wt.depth = initial_wtable)
Error in node_num_ind:(length(profile_data1)) : argument of length 0

**Comment by shoebodh** [comment]
fiexed in revision
